In [2]:
import numpy as np

### Program 1 - Get all odd numbers from an array and then convert them to -1

In [3]:
a=np.arange(10)

odd_numbers= a[a% 2 != 0]
print(odd_numbers)

a[odd_numbers]=-1

print(a)

[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Program 2 - Convert array to boolean array where positive value are True

In [4]:
a=np.array([0,-1,3,-8,-2,1,0])

boolean_array= a >= 0
print(boolean_array)

[ True False  True False False  True  True]


### Program 3 - Replace all even numbers in an array with their negatives

In [5]:
a=np.arange(0,11)

a[a%2==0] *= -1
print(a)


[  0   1  -2   3  -4   5  -6   7  -8   9 -10]


### Program 4 - Normalize a matrix (Subtract mean and divide by std dev)

In [6]:
a=np.random.random((3,3))
normalized_matrix= (a-np.mean(a))/np.std(a)
print(normalized_matrix)

[[-0.50303726  0.99489847  1.14830904]
 [-0.32917025  1.0674563   0.2349173 ]
 [-1.76130851 -1.33989786  0.48783277]]


### Program 5 - Invert the numpy Array

In [17]:
a=np.random.randint(0,10,(10,))
print(a)
a=a[::-1]
print(a)

[9 8 5 9 2 4 4 1 1 0]
[0 1 1 4 4 2 9 5 8 9]


### Program 6 - Find indices of the Maximum and Minimum value in a matrix