### Numpy Basics

Numpy is a multidimensional array library. It can be used to store 1d, 2d, 3d arrays etc. 

Numpy has much faster processing compared to lists so it is more benficial to use numpy for large datasets.

Numpy can be used for Mathematics, Plotting, is used for a lot of backend libraries like pandas, and Machine Learning.

In [1]:
import numpy as np

In [6]:
a=np.array([1,2,3])
print(a)

b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
#Get Dimension of Array - Gives dimesionality of the array
a.ndim

1

In [10]:
#Get Shape - Gives the number of rows and columns
print(b.shape)
a.shape

(2, 3)


(3,)

In [14]:
#Get Size - Gives the number of elements
b.size

6

### Accessing and Changing specific rows, elements, columns etc.

In [18]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
print(a[1,2]) # Get specific element using indexes [row, column]

print(a[0,:]) # Get entire row

print(a[:,0]) # Get entire column

8
[1 2 3 4 5]
[1 6]


In [22]:
print(a[0,0:6:2]) # Using step index to skip elements [start index: end index: step index]

[1 3 5]


In [26]:
# changing element

a[1,3]=15

#changing column
a[:,1]=120
print(a)

[[  1 120   3   4   5]
 [  6 120   8  15  10]]


### Initializing Different Types of Arrays

In [32]:
b=np.zeros((2,3)) # Initializing a zero array with a set shape
#print(b)

c=np.ones((2,6)) # Initializing a ones array with set shape
#print(c)

d=np.full((2,2),99) # Initializing an array with a specific number
#print(d)

e=np.full_like(b,4) # Can create new array using shape of an exisitng one
#print(e)

[[4. 4. 4.]
 [4. 4. 4.]]


In [38]:
print(np.random.rand(4,2)) # Gives a array with random numbers between 0 to 1 using an exisiting shape

print(np.random.randint(2,7,size=(3,3))) #Gives a random integer array based on a shape

[[0.25588963 0.00160394]
 [0.32776581 0.48748474]
 [0.15410432 0.27102498]
 [0.5829282  0.77018259]]
[[4 3 2]
 [4 6 2]
 [6 4 6]]


In [45]:
# Sample problem

output = np.ones((5,5))
z= np.zeros((3,3))
z[1,1]=9
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Mathematics

In [48]:
a=np.array([1,2,3])
print(a)

print(a+2) # Does the mathematical expression on the entire array
print(a-2)
print(a*2)
print(a/2)

[1 2 3]
[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]


In [50]:
b=np.array([0,1,0])
a+b # All the same mathematical expressions can be done between the 2 arrays

array([1, 3, 3])

In [54]:
a=np.ones((2,3))


b=np.full((3,2),2)


np.matmul(a,b) # Used for matrix multiplication

array([[6., 6.],
       [6., 6.]])

In [58]:
c=np.identity(3)
print(np.linalg.det(c)) # similarly inverse, transpose, eigen can done

1.0


In [63]:
stats=np.array([[1,2,3],[4,5,6]])

print(np.min(stats)) # Gives min value in array
print(np.max(stats)) # Gives max value n array
print(np.min(stats, axis=1)) # gives min per row
print(np.sum(stats)) #Gives sum of matrix, adding axis will give sum of rows and columns

1
6
[1 4]
21


### Reorganizing Arrays

In [67]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after= np.reshape(before,(4,2)) # Should contain the same number of values
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [72]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

print(np.vstack((v1,v2,v2,v2))) # vertically stacking arrays
print(np.hstack((v1,v2))) # horizontally stacking arrays

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


### Miscellaneous

Load Data from file - Use function np.getfromtxt(filename,delimeter) to load the data present in your text file into a numpy array

Change data type - Use function np.astype() to change the datatype of an array



In [78]:
#Boolean Masking

print(v1>3)# gives an array where value matches the condition

v1[v1>3] # gives the elements where the condiiton is met



[False False False  True]


array([4])

In [86]:
a=np.array([[4,7,3,7,9,2],[1,9,5,3,5,2],[6,8,1,3,0,1]])
print(a)

print(np.any(a>4,axis=0)) # Gives the columns that match the condition if any element of column matches then gives true

print(np.all(a>4,axis=0)) # Gives true if all elements of a column match the condiiton

[[4 7 3 7 9 2]
 [1 9 5 3 5 2]
 [6 8 1 3 0 1]]
[ True  True  True  True  True False]
[False  True False False False False]
